services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pwd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    secrets:
      - db_pwd
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      VERSION: "0.0.1"
    depends_on:
      db:
        condition: service_completed_successfully
secrets:
  db_pwd:
    file: secret/db_pwd.txt